/**
 * Re-exports of the ts-rs output in ../bindings. Import domain types from here, never
 * from ../bindings directly — this is the one file that fails to compile when a Rust
 * type is renamed or removed.
 *
 * Phase 1 is the first real consumer: the grid renders PartsPage/PartCard straight off
 * the wire. Nothing may hand-write a matching interface instead — a duplicate compiles
 * happily after the Rust type changes underneath it, which is exactly what the bindings
 * staleness gate exists to prevent.
 */
export type { Approximate } from '../bindings/Approximate'
export type { Delta } from '../bindings/Delta'
export type { FacetValue } from '../bindings/FacetValue'
export type { Facets } from '../bindings/Facets'
export type { AssemblyNode } from '../bindings/AssemblyNode'
export type { AssemblyTree } from '../bindings/AssemblyTree'
export type { Entity } from '../bindings/Entity'
export type { Pmi } from '../bindings/Pmi'
export type { PmiFace } from '../bindings/PmiFace'
export type { BatchId } from '../bindings/BatchId'
export type { BatchStatus } from '../bindings/BatchStatus'
export type { BlobHash } from '../bindings/BlobHash'
export type { FolderId } from '../bindings/FolderId'
export type { FolderNode } from '../bindings/FolderNode'
export type { FolderPatch } from '../bindings/FolderPatch'
export type { FilterSearch } from '../bindings/FilterSearch'
export type { CustomField } from '../bindings/CustomField'
export type { CustomFieldChange } from '../bindings/CustomFieldChange'
export type { FieldKind } from '../bindings/FieldKind'
export type { NewCustomField } from '../bindings/NewCustomField'
export type { SetFieldValue } from '../bindings/SetFieldValue'
export type { NewSavedFilter } from '../bindings/NewSavedFilter'
export type { SavedFilter } from '../bindings/SavedFilter'
export type { SavedFilterId } from '../bindings/SavedFilterId'
export type { MoveDirection } from '../bindings/MoveDirection'
export type { MoveSavedFilter } from '../bindings/MoveSavedFilter'
export type { RenameSavedFilter } from '../bindings/RenameSavedFilter'
export type { InstanceStorageView } from '../bindings/InstanceStorageView'
export type { RenderCacheFreedView } from '../bindings/RenderCacheFreedView'
export type { BundlePlan } from '../bindings/BundlePlan'
export type { PartImage } from '../bindings/PartImage'
export type { FetchImageRequest } from '../bindings/FetchImageRequest'
export type { NewSource } from '../bindings/NewSource'
export type { PartImageId } from '../bindings/PartImageId'
export type { PartSource } from '../bindings/PartSource'
export type { SetFraming } from '../bindings/SetFraming'
export type { SetMaterials } from '../bindings/SetMaterials'
export type { SetTags } from '../bindings/SetTags'
export type { StoredImage } from '../bindings/StoredImage'
export type { NewFolder } from '../bindings/NewFolder'
export type { LibraryId } from '../bindings/LibraryId'
export type { LibraryMode } from '../bindings/LibraryMode'
export type { LibrarySettings } from '../bindings/LibrarySettings'
export type { LibrarySummary } from '../bindings/LibrarySummary'
export type { NewLibrary } from '../bindings/NewLibrary'
export type { LibraryStorage } from '../bindings/LibraryStorage'
export type { MovePart } from '../bindings/MovePart'
export type { PartCard } from '../bindings/PartCard'
export type { PartDetail } from '../bindings/PartDetail'
export type { PartLock } from '../bindings/PartLock'
export type { ReleaseLock } from '../bindings/ReleaseLock'
export type { PartRevision } from '../bindings/PartRevision'
export type { PartId } from '../bindings/PartId'
export type { PartsPage } from '../bindings/PartsPage'
export type { PurgeResult } from '../bindings/PurgeResult'
export type { PartSummary } from '../bindings/PartSummary'
export type { RevisionId } from '../bindings/RevisionId'
export type { RevisionOrigin } from '../bindings/RevisionOrigin'
export type { RevisionDiff } from '../bindings/RevisionDiff'
export type { ScanAccepted } from '../bindings/ScanAccepted'
export type { ChunkAccepted } from '../bindings/ChunkAccepted'
export type { UploadFile } from '../bindings/UploadFile'
export type { UploadManifest } from '../bindings/UploadManifest'
export type { UploadPlan } from '../bindings/UploadPlan'
export type { FailurePage } from '../bindings/FailurePage'
export type { JobFailure } from '../bindings/JobFailure'
export type { JobId } from '../bindings/JobId'
export type { RetryAccepted } from '../bindings/RetryAccepted'
export type { RungReady } from '../bindings/RungReady'
