// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `POST` body: what two people paste to each other.
 */
export type AddPeer = { deviceId: string, address: string, };
