// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryId } from "./LibraryId";

/**
 * One event on the stream, sent as the JSON of an SSE `data:` line.
 */
export type AppEvent = { "type": "changed", library: LibraryId, } | { "type": "resync" };
