// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wraps a measured value with whether it came from an analytic B-rep entity or from
 * tessellated geometry.
 *
 * This is a type rather than a UI convention because `CLAUDE.md` makes it
 * non-negotiable: mesh-derived measurements are labelled "approximate" in the UI,
 * always. Making the flag inseparable from the value means a caller cannot render one
 * without the other.
 */
export type Approximate<T> = { value: T, approximate: boolean, };
