// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssemblyNode } from "./AssemblyNode";

/**
 * An assembly's tree as the CAD file describes it. `None` on [`KernelOutput::structure`]
 * for a mesh, which has no tree to describe.
 */
export type AssemblyTree = { roots: Array<AssemblyNode>, 
/**
 * Leaves: placed parts, counting every instance.
 */
parts: number, 
/**
 * Distinct part definitions the leaves are instances of.
 */
prototypes: number, };
