// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AssemblyNode = { name: string, prototype: string, 
/**
 * Row-major 4×4, relative to the parent node.
 */
transform: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], children: Array<AssemblyNode>, };
