// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 *Groups the jobs one scan created. A grouping column, not an entity: nothing is stored under this id, so nothing under it can go stale.
 */
export type BatchId = string;
