// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchId } from "./BatchId";
import type { JobFailure } from "./JobFailure";
import type { LibraryId } from "./LibraryId";

/**
 * What a scan turned into.
 *
 * `ingested`, `skipped` and the per-file failures are slice 1's `ScanReport` counters,
 * relocated from a response body that vanished with the connection to rows that do not.
 */
export type BatchStatus = { batchId: BatchId, libraryId: LibraryId, total: number, pending: number, running: number, ingested: number, skipped: number, rendered: number, 
/**
 * How many `scan_directory` jobs in this batch have finished their walk — in
 * practice 0 or 1, since a scan enqueues one and its children join the same batch.
 *
 * Exposed so the progress line can say *files*. `total` counts jobs, and the walk is
 * a job; reporting it as a file made a three-file directory read "Scanning — 1 of 4
 * files", which `CLAUDE.md`'s measurement rule forbids. Subtracting this from both
 * halves is exact, where subtracting a hardcoded 1 would encode "every batch has a
 * walk" in the frontend — untrue of a render sweep.
 */
scanned: number, 
/**
 * How many `migrate_storage` jobs in this batch have finished moving a slice of
 * the old content-addressed store into its parts' own directories.
 *
 * A migration chains itself the same way a scan chains its walk (`total` grows as
 * each run re-enqueues the next slice), and it ingests nothing and skips nothing —
 * borrowing `ingested` for it would put moved-not-added files in the grid's "added"
 * column, and `scanned` already means something else. This is what lets the
 * progress line, and the batch-kind guess above it, tell a migration apart from
 * both without a new job kind on the wire.
 */
migrated: number, failedTotal: number, 
/**
 * The first 100 failures, ordered by creation, so the list is stable across polls
 * rather than reshuffling under the reader. `failed_total` is the real count.
 */
failed: Array<JobFailure>, 
/**
 * RFC 3339 on the wire, exactly like `PartCard.created_at` — ts-rs renders a
 * `jiff::Timestamp` as `string`. The microsecond hop is a *database-read* workaround
 * (sqlx 0.9 ships `chrono` and `time`, not `jiff`), never a wire format:
 * `lapidary-db` selects microseconds and rebuilds with `Timestamp::from_microsecond`
 * before this type is ever constructed, which is what `PgParts::page` already does.
 */
startedAt: string, 
/**
 * Set only once no job in the batch is pending or running.
 */
finishedAt: string | null, };
