// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchId } from "./BatchId";
import type { JobFailure } from "./JobFailure";
import type { LibraryId } from "./LibraryId";

/**
 * What a scan turned into.
 *
 * `ingested`, `skipped` and the per-file failures are slice 1's `ScanReport` counters,
 * relocated from a response body that vanished with the connection to rows that do not.
 */
export type BatchStatus = { batchId: BatchId, libraryId: LibraryId, total: number, pending: number, running: number, ingested: number, skipped: number, failedTotal: number, 
/**
 * The first 100 failures, ordered by creation, so the list is stable across polls
 * rather than reshuffling under the reader. `failed_total` is the real count.
 */
failed: Array<JobFailure>, 
/**
 * RFC 3339 on the wire, exactly like `PartCard.created_at` -- ts-rs renders a
 * `jiff::Timestamp` as `string`. The microsecond hop is a *database-read* workaround
 * (sqlx 0.9 ships `chrono` and `time`, not `jiff`), never a wire format:
 * `lapidary-db` selects microseconds and rebuilds with `Timestamp::from_microsecond`
 * before this type is ever constructed, which is what `PgParts::page` already does.
 */
startedAt: string, 
/**
 * Set only once no job in the batch is pending or running.
 */
finishedAt: string | null, };
