// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchId } from "./BatchId";
import type { JobFailure } from "./JobFailure";
import type { LibraryId } from "./LibraryId";

/**
 * What a scan turned into.
 *
 * `ingested`, `skipped` and the per-file failures are slice 1's `ScanReport` counters,
 * relocated from a response body that vanished with the connection to rows that do not.
 */
export type BatchStatus = { batchId: BatchId, libraryId: LibraryId, total: number, pending: number, running: number, ingested: number, skipped: number, rendered: number, 
/**
 * How many `scan_directory` jobs in this batch have finished their walk — in
 * practice 0 or 1, since a scan enqueues one and its children join the same batch.
 *
 * Exposed so the progress line can say *files*. `total` counts jobs, and the walk is
 * a job; reporting it as a file made a three-file directory read "Scanning — 1 of 4
 * files", which `CLAUDE.md`'s measurement rule forbids. Subtracting this from both
 * halves is exact, where subtracting a hardcoded 1 would encode "every batch has a
 * walk" in the frontend — untrue of a render sweep.
 */
scanned: number, 
/**
 * How many `migrate_storage` jobs in this batch have finished moving a slice of
 * the old content-addressed store into its parts' own directories.
 *
 * A migration chains itself the same way a scan chains its walk (`total` grows as
 * each run re-enqueues the next slice), and it ingests nothing and skips nothing —
 * borrowing `ingested` for it would put moved-not-added files in the grid's "added"
 * column, and `scanned` already means something else.
 *
 * This counts settled OUTCOMES, not rows, so it is 0 for every migration at the
 * instant it begins — and the worker's startup enqueue is the only way a
 * `migrate_storage` batch can exist, so every migration a browser can watch starts
 * inside that window. `migrating` below is what the batch-kind guess actually reads
 * to tell a fresh migration apart from a fresh scan; this field is left for
 * whatever eventually reports how much of one migration run has settled.
 */
migrated: number, 
/**
 * How many `migrate_storage` job ROWS exist in this batch, settled or not —
 * `count(*) FILTER (WHERE kind = 'migrate_storage')`, not `... WHERE outcome =
 * 'migrated'`. Non-zero from the moment the first `migrate_storage` row is
 * inserted, unlike `migrated` above, which stays 0 until one finishes — and since
 * `HASHES_PER_RUN` (200) makes the first run the slowest on a large corpus, that is
 * exactly the batch where the gap between "exists" and "has settled one" is widest.
 * This is the field the batch-kind guess reads.
 */
migrating: number, failedTotal: number, 
/**
 * The first 100 failures, ordered by creation, so the list is stable across polls
 * rather than reshuffling under the reader. `failed_total` is the real count.
 */
failed: Array<JobFailure>, 
/**
 * RFC 3339 on the wire, exactly like `PartCard.created_at` — ts-rs renders a
 * `jiff::Timestamp` as `string`. The microsecond hop is a *database-read* workaround
 * (sqlx 0.9 ships `chrono` and `time`, not `jiff`), never a wire format:
 * `lapidary-db` selects microseconds and rebuilds with `Timestamp::from_microsecond`
 * before this type is ever constructed, which is what `PgParts::page` already does.
 */
startedAt: string, 
/**
 * Set only once no job in the batch is pending or running.
 */
finishedAt: string | null, };
