// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A BLAKE3 content hash. Content addressing is not authorization — holding one of
 * these never implies the right to read the blob it names.
 *
 * Serialises as a 64-character hex string, not as a byte array, so the wire format
 * and the generated TypeScript type agree.
 */
export type BlobHash = string;
