// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a bundle of the selected parts holds, said before the download starts.
 */
export type BundlePlan = { parts: number, revisions: number, 
/**
 * The archive's exact length: the download's `Content-Length`.
 */
bytes: number, };
