// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LockId } from "./LockId";

/**
 * `POST /api/parts/{id}/checkin`'s body.
 */
export type Checkin = { lock: LockId, };
