// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PartLock } from "./PartLock";
import type { RevisionId } from "./RevisionId";

/**
 * What a check-out hands back: the lock, and the revision it was taken on — the one the
 * holder's copy is of.
 */
export type CheckedOut = { lock: PartLock, revision: RevisionId, };
