// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much of a staged file the server holds. The answer to a chunk, and the answer to
 * a rejected offset — a resuming client reads the same field either way.
 */
export type ChunkAccepted = { received: bigint, };
