// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldKind } from "./FieldKind";

/**
 * One field, as a library defines it.
 */
export type CustomField = { 
/**
 * The field's name in the data: never renamed, and what a filter and a part's value are keyed by.
 */
key: string, label: string, kind: FieldKind, 
/**
 * A choice's options, in order. Empty for the other kinds.
 */
options: Array<string>, 
/**
 * Offered as a grid filter.
 */
indexed: boolean, };
