// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `PATCH /api/libraries/{library}/fields/{key}`: what changes. A field's key and kind never do.
 */
export type CustomFieldChange = { label?: string, options?: Array<string>, indexed?: boolean, };
