// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `PUT /api/shares/{id}/grants/{device}`'s body.
 */
export type DecideGrant = { granted: boolean, };
