// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One figure's change between two revisions.
 */
export type Delta = { from: number, to: number, 
/**
 * `to - from`.
 */
change: number, 
/**
 * The change as a percentage of `from`. `None` when `from` is zero: a percentage of
 * nothing is not a number anyone can read.
 */
percent: number | null, 
/**
 * When either figure is mesh-derived. A difference is no more exact than the less exact
 * of the two figures it was taken between, and `CLAUDE.md` says the UI labels that.
 */
approximate: boolean, };
