// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The duplicates review queue in brief; the duplicates page holds the groups themselves.
 */
export type DuplicateSummary = { clusters: number, 
/**
 * Parts with no shape profile yet, so not compared.
 */
unprofiled: number, };
