// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PartCard } from "./PartCard";

/**
 * One group of parts that look like duplicates of each other.
 */
export type DuplicateCluster = { 
/**
 * Two or more, largest `size_mm` first.
 */
parts: Array<PartCard>, 
/**
 * Every part in the group has the same source bytes, so there is no shape judgement in it.
 */
identical: boolean, };
