// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DuplicateCluster } from "./DuplicateCluster";

/**
 * `GET /api/libraries/{id}/duplicates`: the review queue. Computed when read, never stored; a pair somebody
 * called `variant` or `distinct` is never in it.
 */
export type DuplicateClusters = { clusters: Array<DuplicateCluster>, 
/**
 * Live parts with no current profile yet, which could not be compared. The page says so rather than
 * implying the library was checked in full.
 */
unprofiled: number, };
