// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Analytic B-rep entities — axes, radii, normals — that measurement snaps to.
 *
 * Typed, never the `Vec<String>` it once was: measurement cannot snap to
 * `"CYLINDRICAL_SURFACE:22.000"` without parsing it back out of a string. A mesh has none,
 * and that emptiness is load-bearing — it is what stops tessellated numbers being presented
 * as exact. `OcctKernel` fills it from `occt-bridge`'s `entities.json`.
 *
 * Each entity is in its prototype's own coordinates, once per prototype rather than once per
 * placed instance: the [`AssemblyTree`](crate::AssemblyTree) beside them holds the transforms
 * that place it. `face` and `edge` are 1-based indices into the prototype's faces and edges in
 * OCCT's map order.
 */
export type Entity = { "type": "plane", prototype: string, face: number, origin: [number, number, number], normal: [number, number, number], } | { "type": "cylinder", prototype: string, face: number, radius: number, origin: [number, number, number], axis: [number, number, number], } | { "type": "cone", prototype: string, face: number, ref_radius: number, semi_angle_rad: number, origin: [number, number, number], axis: [number, number, number], } | { "type": "sphere", prototype: string, face: number, radius: number, center: [number, number, number], } | { "type": "torus", prototype: string, face: number, major_radius: number, minor_radius: number, origin: [number, number, number], axis: [number, number, number], } | { "type": "circle", prototype: string, edge: number, radius: number, center: [number, number, number], normal: [number, number, number], };
