// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FacetValue } from "./FacetValue";
import type { FieldFacet } from "./FieldFacet";

export type Facets = { formats: Array<FacetValue>, 
/**
 * The materials the parts' files declare. Empty for a library of meshes, which declare none.
 */
materials: Array<FacetValue>, 
/**
 * The tags people gave the parts. Empty until somebody tags one.
 */
tags: Array<FacetValue>, 
/**
 * Each choice field offered as a filter, with how many of the parts hold each of its values. A field
 * filter never narrows its own field's counts.
 */
fields: Array<FieldFacet>, };
