// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FacetValue } from "./FacetValue";

export type Facets = { formats: Array<FacetValue>, 
/**
 * The materials the parts' files declare. Empty for a library of meshes, which declare none.
 */
materials: Array<FacetValue>, 
/**
 * The tags people gave the parts. Empty until somebody tags one.
 */
tags: Array<FacetValue>, };
