// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which facet a [`Widget::Facet`] counts.
 */
export type FacetKind = "format" | "material" | "tag";
