// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One source format, and how many of the grid's parts carry it. `count` is `null` past the
 * exact-count threshold, where only the values that occur are shown.
 */
export type FacetValue = { value: string, count: number | null, };
