// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobFailure } from "./JobFailure";
import type { JobId } from "./JobId";

/**
 * One page of a batch's failures, past the sample `BatchStatus` carries.
 */
export type FailurePage = { failed: Array<JobFailure>, 
/**
 * The last job on a full page, to ask for the next one with. `None` once a page comes
 * back short, which proves there is nothing after it.
 */
next: JobId | null, };
