// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The address to fetch from. An object rather than a bare string so that the crop and fit
 * fields, which live on the row and not in the bytes, have somewhere to go later.
 */
export type FetchImageRequest = { url: string, };
