// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FacetValue } from "./FacetValue";

/**
 * One choice field's values among the grid's parts, each as a [`FacetValue`]. A value no part holds is left
 * out.
 */
export type FieldFacet = { key: string, values: Array<FacetValue>, };
