// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FolderId } from "./FolderId";

/**
 * The grid's filters, as its URL carries them. An absent field is no filter on it, and a field
 * the grid does not filter by is refused rather than kept.
 */
export type FilterSearch = { q?: string, folderId?: FolderId, format?: string, material?: string, tag?: string, };
