// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PartCard } from "./PartCard";

/**
 * A saved filter's parts, with its name as it is now — renamed since the layout was saved, it shows the new
 * one.
 */
export type FilteredParts = { name: string, parts: Array<PartCard>, };
