// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PartCard } from "./PartCard";
import type { PartId } from "./PartId";

/**
 * One entry of `GET /api/libraries/{id}/folds`: a removed part that was folded, and the part it was folded
 * into, for the removed page to say where it went.
 */
export type Fold = { part: PartId, into: PartCard, };
