// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FolderId } from "./FolderId";

/**
 * `PATCH /api/folders/{id}` — rename, reparent, or both.
 *
 * `parentId` is a double `Option` because the two absences are different requests:
 * leaving the field out means "do not move it", and sending `null` means "move it to the
 * library root". Collapsing them would make every rename also move the folder to the root,
 * which is the kind of silent data change this project treats as a defect, not a default.
 *
 * **Both fields are `#[ts(optional = nullable)]`, and for `parentId` that is the whole
 * point.** TypeScript can express the three states this type has — `{}`, `{parentId:
 * null}` and `{parentId: id}` — only as an *optional* property, because an omitted key
 * and a `null` one are different values there in a way they are not in most languages.
 * Exported as `parentId?: FolderId | null`, a client that spreads an object with
 * `parentId: undefined` sends nothing, and one that means the root has to write `null` on
 * purpose. Bound to `T | null` instead — ts-rs's default for `Option` — the two states
 * would collapse and every rename would quietly move its category to the library root.
 */
export type FolderPatch = { name?: string, parentId?: FolderId | null | null, };
