// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PartId } from "./PartId";

/**
 * The `POST /api/parts/{id}/fold` body: fold this part into `into`. In one transaction this part is removed,
 * by the same rule as any removal, and a `foldedInto` link records the part kept. Nothing is moved and nothing
 * is deleted; Restore brings it back. Both parts must be in one library.
 */
export type FoldPart = { into: PartId, };
