// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `PATCH /api/folders/{id}` — rename a category.
 *
 * A category cannot move under another one yet (`DATA.md`, "Re-parenting a category"), so
 * `parentId` is read only to be refused, and it is left out of the TypeScript type so that no
 * client here can send it. Its double `Option` tells a key that is present from one that is
 * absent, so a request naming the library root with `null` is refused, not taken for a rename.
 */
export type FolderPatch = { name?: string, };
