// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FolderId } from "./FolderId";

/**
 * One node of the tree, flat. The client nests them by `parentId`.
 *
 * Flat rather than nested, whole rather than a level at a time: at corpus scale the tree
 * is hundreds of rows, a lazy tree costs a round trip per expand on the one interaction
 * that has to feel instant (design §10), and a nested JSON shape built in SQL would be a
 * second structure to keep in step with the TypeScript one.
 */
export type FolderNode = { id: FolderId, 
/**
 * `null` at the library root. The tree has no synthetic root node — "All models" is a
 * row the sidebar draws itself, because it stands for the absence of a filter and
 * there is no id that means "no category".
 */
parentId: FolderId | null, name: string, 
/**
 * Live models in this category **and every category under it**.
 *
 * It rides along on every node so that one tree request answers the whole sidebar
 * including every delete confirmation — the requirement is that a destructive
 * confirmation names what it affects, and a count fetched per folder would be N
 * requests for a panel that is one. Subtree-inclusive because the delete cascades that
 * way, and it counts only models the grid would show, so the dialog cannot contradict
 * the screen beside it.
 *
 * `number`, not `bigint`: ts-rs 12 maps a 64-bit integer to `bigint`, which
 * `JSON.parse` never produces. Same override, same reason, as
 * `PartSummary::sourceBytes`.
 */
partCount: number, };
