// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 *Identifies a category folder. Location, never identity — a part's identity is its `source_path`.
 */
export type FolderId = string;
