// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlobHash } from "./BlobHash";

/**
 * `POST /api/libraries/{id}/imports`'s body: a bundle already sent through the chunked upload.
 */
export type ImportRequest = { blake3: BlobHash, 
/**
 * The file's own name, which the batch names a refused bundle by.
 */
name: string, };
