// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the whole store holds, and where it is.
 *
 * The question `LibraryStorage` cannot answer. That one is per library and deliberately
 * **not** `du`: it charges a blob two libraries share to both of them, and it can show
 * quarantined bytes to nobody because a quarantined blob is keyed by hash and the part
 * that said which library it belonged to is the part that was purged. So a person adding
 * up the panels and comparing the result to their disk finds a discrepancy, and
 * `PgParts::storage_totals`'s own doc predicts it: *"someone will eventually run `du`."*
 *
 * This is the answer to that, and it reports both halves rather than picking one:
 * `tracked*` is what the database knows, exactly and instantly; `on_disk_bytes` is a real
 * walk of the root, which is the number `du` gives. Neither is wrong and they do not
 * agree, and the difference is what a person actually wants to see.
 */
export type InstanceStorageView = { 
/**
 * Every live model file across every library. One file per model, no deduplication.
 */
sourceBytes: number, 
/**
 * Rungs and inline thumbnails, **each blob counted once** however many libraries point
 * at it — where the per-library figure charges it to each of them in full.
 */
derivativeBytes: number, 
/**
 * Soft-deleted parts. On the disk, and back the moment somebody restores them.
 */
removedBytes: number, 
/**
 * Purged and inside the thirty-day hold. Bytes no per-library panel can admit to.
 */
quarantinedBytes: number, 
/**
 * A real walk of the storage root, or `None` when one was not asked for.
 *
 * Behind `?onDisk=true` because it costs a `stat` per file: instant on the 156-part
 * library this was written against, seconds on a corpus. The default answer is the
 * one that is free.
 */
onDiskBytes: number | null, 
/**
 * Where the store is **on the host**, when the deployment has said.
 *
 * `None` unless `LAPIDARY_HOST_STORAGE_ROOT` names an absolute path, and the reason is
 * that this process genuinely cannot work it out. The api sees the store at
 * `/var/lib/lapidary`, which is a bind mount and a path that exists nowhere on the
 * machine the user is sitting at. Reporting it would be worse than reporting nothing:
 * they would paste it into a file manager and find no such directory.
 */
hostStorageRoot: string | null, };
