// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeerShareId } from "./PeerShareId";

/**
 * Somebody the owner of a shared folder has introduced, waiting for an answer (sharing S6).
 */
export type Introduction = { 
/**
 * The mirrored folder they were introduced in: accepting is about that folder.
 */
shareId: PeerShareId, shareName: string, deviceId: string, 
/**
 * What they call themselves, as the folder's owner last heard it.
 */
name: string | null, address: string, 
/**
 * Who introduced them: the folder's owner.
 */
introducedBy: string, introducerName: string | null, };
