// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobId } from "./JobId";

export type JobFailure = { 
/**
 * The job that failed, so one file can be retried by itself.
 */
job: JobId, path: string, 
/**
 * The handler's message, verbatim. A person reads this in the UI, so it says what
 * broke and what to do about it.
 */
reason: string, attempts: number, };
