// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JobFailure = { path: string, 
/**
 * The handler's message, verbatim. A person reads this in the UI, so it says what
 * broke and what to do about it.
 */
reason: string, attempts: number, };
