// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryId } from "./LibraryId";
import type { LibraryMode } from "./LibraryMode";

/**
 * One library in the switcher.
 *
 * `partCount` rides along so the control can say which library has anything in it without
 * a request per row — the same reason `FolderNode` carries one.
 */
export type LibrarySummary = { id: LibraryId, name: string, 
/**
 * `hobby` or `controlled`. **Nothing reads it yet** — governance is Phase 8 — and it is
 * on the wire because a switcher that shows which libraries are controlled is the point
 * at which the column stops being decorative. Until then it is a label.
 */
mode: LibraryMode, partCount: number, };
