// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A library's search language, as `library.language` holds it.
 */
export type LibraryLanguage = "simple" | "turkish";
