// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryId } from "./LibraryId";
import type { LibraryMode } from "./LibraryMode";

/**
 * One library in the switcher.
 *
 * `partCount` rides along so the control can say which library has anything in it without
 * a request per row — the same reason `FolderNode` carries one.
 */
export type LibrarySummary = { id: LibraryId, name: string, 
/**
 * `hobby` or `controlled`. A controlled library keeps a changed file as a new revision
 * (Phase 4 slice 1); a hobby library says the change was not kept. States and approvals
 * are still Phase 8.
 */
mode: LibraryMode, partCount: number, };
