// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Governance is opt-in per library. Hobby libraries have no revisions, states or
 * approvals; flipping a library to `Controlled` turns that machinery on.
 */
export type LibraryMode = "hobby" | "controlled";
