// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a library costs, the library-level half of the figures on every card.
 *
 * Both totals are bytes on disk after compression, deduplicated — see
 * `PgParts::storage_totals`, which is where the accounting is written down. `number`,
 * not `bigint`: serde puts a JSON number on the wire, and ts-rs 12 would otherwise
 * promise the frontend something `JSON.parse` never produces.
 */
export type LibraryStorage = { sourceBytes: number, derivativeBytes: number, 
/**
 * Derivative bytes ÷ source bytes. `None` for a library holding no source bytes,
 * where the division has no answer — a library with nothing in it, and a `0` there
 * would read as "derivatives cost nothing", which is a different claim.
 *
 * Sent rather than left to the client because the direction is the whole meaning:
 * this is the figure that made slice 4's 92.5% drop legible (spec §4), and a second
 * consumer dividing the other way would report the same library twice, differently.
 */
derivativeRatio: number | null, };
