// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `PATCH` body, and the `200` echo of it.
 *
 * Exported now that `web/` sends it. It was deliberately not `#[ts(export)]` while no
 * caller existed — an exported type nobody imports is a binding to keep in step for no
 * one — and the grid's action bar is that caller, so the reason has expired. Hand-writing
 * `{ autoThumbnail: boolean }` in `web/src/lib/api.ts` instead would be a shape that
 * keeps compiling after this field is renamed, which is the one thing `web/src/lib/types.ts`
 * exists to make impossible.
 */
export type LibrarySettings = { autoThumbnail: boolean, };
