// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What sharing a category would offer, counted before anybody confirms.
 */
export type LicenceWarning = { parts: bigint, 
/**
 * Parts with no licence recorded.
 */
unrecorded: bigint, 
/**
 * Parts whose licence says non-commercial.
 */
nonCommercial: bigint, };
