// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PartCard } from "./PartCard";

/**
 * `GET /api/parts/{id}/likeness`: the parts that look like this one, each list closest first.
 */
export type Likeness = { 
/**
 * Whether this part has a current shape profile. `false` until the worker has made one — then
 * `near_duplicates` and `similar` are empty because nothing is known yet, not because nothing is alike.
 */
profiled: boolean, 
/**
 * The same bytes: parts in this library whose current source file has this one's hash. Needs no profile.
 */
identical: Array<PartCard>, 
/**
 * Alike in shape and within 2% in size ([`lapidary_core::shape::is_near_duplicate`]), and not yet decided
 * about.
 */
nearDuplicates: Array<PartCard>, 
/**
 * "More like this": the closest shapes whatever their size, a few, excluding the lists above.
 */
similar: Array<PartCard>, 
/**
 * Parts somebody said belong with this one.
 */
variants: Array<PartCard>, };
