// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 *Identifies one check-out of a part. An identifier, not a secret: there is no auth yet (Phase 4 slice 1 spec §5).
 */
export type LockId = string;
