// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One material's density in a library.
 */
export type MaterialDensity = { material: string, densityKgM3: number, };
