// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The figures a kernel measured. A mesh's are all tessellated; a CAD kernel reads some
 * off the B-rep instead, and [`MeasurementProvenance`] travels beside them saying which.
 */
export type MeshMeasurements = { bboxMm: [number, number, number], triangleCount: number, surfaceAreaMm2: number, 
/**
 * `None` when the mesh is not watertight. Signed-volume integration over an open
 * mesh produces a plausible-looking number with no meaning, and a wrong number is
 * worse than no number.
 */
volumeMm3: number | null, isWatertight: boolean, };
