// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeerShareId } from "./PeerShareId";

/**
 * Somebody else's share, as mirrored here.
 */
export type MirroredShare = { id: PeerShareId, deviceId: string, 
/**
 * What the sharer calls themselves, as their last hello said.
 */
sharer: string | null, name: string, partCount: number, 
/**
 * When its whole catalogue was last read. `None` until it has been.
 */
syncedAt: string | null, 
/**
 * The member this copy was read from, when it was not read from the folder's owner, and what they call
 * themselves. `None` is the ordinary case: read from its owner (S7).
 */
readFrom: string | null, readFromName: string | null, 
/**
 * When the copy shown here was read from the folder's owner, by whoever read it.
 */
asOf: string | null, 
/**
 * Whether this installation passes the folder's files on to its other people (S8).
 */
seeding: boolean, 
/**
 * How many of the folder's files this installation holds, and how many the folder lists — what the
 * folder's own page says can be served from here. Left out of a list of folders, which does not count
 * them: a list of ten folders is not worth ten counting queries.
 */
heldFiles?: number, listedFiles?: number, };
