// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MirroredPart } from "./MirroredPart";

/**
 * A page of a mirrored share's parts. `next` is the `after` for the page that follows.
 */
export type MirroredPartsPage = { parts: Array<MirroredPart>, next: string | null, };
