// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeerShareId } from "./PeerShareId";

/**
 * Somebody else's share, as mirrored here.
 */
export type MirroredShare = { id: PeerShareId, deviceId: string, 
/**
 * What the sharer calls themselves, as their last hello said.
 */
sharer: string | null, name: string, partCount: number, 
/**
 * When its whole catalogue was last read. `None` until it has been.
 */
syncedAt: string | null, };
