// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MirroredPart = { sourcePath: string, name: string, partNumber: string | null, tags: Array<string>, licences: Array<string>, sizeBytes: number | null, format: string | null, thumbnail: boolean, 
/**
 * Whether this installation already holds that file: the page offers the ones it does not, and says so of
 * the ones it does (S9).
 */
held: boolean, };
