// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MoveDirection } from "./MoveDirection";

/**
 * `POST /api/libraries/{library}/filters/{filter}/move`.
 */
export type MoveSavedFilter = { direction: MoveDirection, };
