// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FolderId } from "./FolderId";

export type MovePart = { 
/**
 * The category to file it under, or `null` for the library root. `null` is a real
 * target and not the absence of one.
 */
folderId: FolderId | null, 
/**
 * The client has seen the collision warning and wants it anyway. Slice 6a decided two
 * parts called `bracket` are the truth; this is how the UI says it knows.
 */
acknowledgeDuplicate: boolean, };
