// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One place up the list, or one place down it.
 */
export type MoveDirection = "up" | "down";
