// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /api/parts/{id}/checkout`'s body.
 */
export type NewCheckout = { 
/**
 * Who is checking the part out, as free text: the agent sends `$USER@$HOSTNAME`.
 */
holder: string, };
