// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldKind } from "./FieldKind";

/**
 * `POST /api/libraries/{id}/fields`.
 */
export type NewCustomField = { key: string, label: string, kind: FieldKind, options?: Array<string>, indexed?: boolean, };
