// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FolderId } from "./FolderId";

/**
 * `POST /api/libraries/{id}/folders` — a category the user typed, not one a scan found.
 */
export type NewFolder = { 
/**
 * Absent or `null` puts it at the library root.
 */
parentId?: FolderId | null, name: string, };
