// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryMode } from "./LibraryMode";

/**
 * What `POST /api/libraries` takes.
 */
export type NewLibrary = { name: string, 
/**
 * Chosen at creation and not asked about later, because later means asking about a
 * library somebody has already filled. Defaults to `hobby`, which is what a library
 * with no governance is.
 */
mode: LibraryMode, };
