// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryLanguage } from "./LibraryLanguage";
import type { LibraryMode } from "./LibraryMode";

/**
 * What `POST /api/libraries` takes.
 */
export type NewLibrary = { name: string, 
/**
 * Chosen at creation and not asked about later, because later means asking about a
 * library somebody has already filled. Defaults to `hobby`, which is what a library
 * with no governance is.
 */
mode: LibraryMode, 
/**
 * The language its search stems words in (`docs/DATA.md` §3.3). Chosen at creation and not
 * changed later, because changing it would rewrite every part's search vector.
 */
language: LibraryLanguage, };
