// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterSearch } from "./FilterSearch";

/**
 * `POST /api/libraries/{id}/filters`.
 */
export type NewSavedFilter = { name: string, search: FilterSearch, };
