// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the form posts. Every field optional; the route refuses one that is entirely empty.
 */
export type NewSource = { url: string | null, vendor: string | null, externalId: string | null, title: string | null, license: string | null, 
/**
 * `number` on the wire, for the reason [`PartSource::price_minor`] gives.
 */
priceMinor: number | null, currency: string | null, };
