// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a job finished. All four are successes: `Skipped` means this library already
 * held this exact file, which is slice 1's hash short-circuit doing its job; `Rendered`
 * means a `derive` job upserted the derivative it was asked to produce; `Scanned` means
 * a `scan_directory` job walked the ingest mount and enqueued what it found.
 *
 * `Scanned` exists because the other three would each be a counter that lies. The
 * database requires a finished job to say how it finished (`job_done_has_outcome`), and
 * a scan job ingests nothing, skips nothing and renders nothing: reporting it as
 * `Skipped` tells a user a file was "already here", `Rendered` makes the grid read the
 * whole batch as a preview render, and `Ingested` claims a part that does not exist.
 */
export type Outcome = "ingested" | "skipped" | "rendered" | "scanned";
