// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a job finished. All five are successes: `Skipped` means this library already
 * held this exact file, which is slice 1's hash short-circuit doing its job; `Rendered`
 * means a `derive` job upserted the derivative it was asked to produce; `Scanned` means
 * a `scan_directory` job walked the ingest mount and enqueued what it found; `Migrated`
 * means a `migrate_storage` job moved a slice of an old content-addressed store into the
 * model directories that replaced it.
 *
 * `Scanned` exists because the other three would each be a counter that lies. The
 * database requires a finished job to say how it finished (`job_done_has_outcome`), and
 * a scan job ingests nothing, skips nothing and renders nothing: reporting it as
 * `Skipped` tells a user a file was "already here", `Rendered` makes the grid read the
 * whole batch as a preview render, and `Ingested` claims a part that does not exist.
 *
 * `Migrated` exists for the same reason one step further on: a `migrate_storage` run
 * indexes nothing new — it moves bytes a part already had from the content-addressed
 * store into that part's own directory. Reporting it as `Ingested` would put files a
 * user already had into the "added" column of a batch they are watching.
 *
 * `Revised` and `Unkept` are the two answers to a file whose bytes changed at a path the
 * library already indexes (Phase 4 slice 1). A controlled library keeps the change as a
 * new revision; a hobby library keeps no revisions and says so. `Unkept` is a notice, not a
 * failure: nothing broke, the new bytes are still where they came from, and a retry could
 * not change the answer — so it is counted here rather than listed as a failed job.
 */
export type Outcome = "ingested" | "skipped" | "rendered" | "scanned" | "migrated" | "revised" | "unkept" | "described";
