// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PartCard } from "./PartCard";
import type { PartId } from "./PartId";

/**
 * A keyset page of the grid.
 */
export type PartsPage = { parts: Array<PartCard>, 
/**
 * Pass back as `after` to fetch the next page. `None` when this page was not
 * full — a short page proves there is nothing left, so there is no id to hand
 * back that would not just fetch another empty page.
 */
next: PartId | null, };
