// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlobHash } from "./BlobHash";
import type { LibraryId } from "./LibraryId";
import type { PartId } from "./PartId";
import type { RevisionId } from "./RevisionId";

/**
 * The grid row, in the shape the spec calls for: identity, part number, thumbnail
 * reference, approximate flag, storage figures, timestamps. Still narrow — the open
 * path reads metadata and derivatives only, and never a source file. The storage
 * fields below are `blob` and `file` *rows*, not bytes: describing a source file is
 * not opening one, and spec §4 wants the cost of a part legible on its card.
 */
export type PartSummary = { id: PartId, library: LibraryId, 
/**
 * The revision the rest of this row describes — the latest one, resolved by the
 * grid query. Carried because a download URL names a revision, not a part: a card
 * cannot link to `GET /api/revisions/{id}/download` without it, and resolving
 * "latest" a second time from the frontend could name a different revision than
 * the numbers beside the link came from.
 */
revision: RevisionId, name: string, partNumber: string | null, 
/**
 * The path this part is known by, which since slice 6a is its identity in the
 * library — two parts called `bracket` in two folders are one name and two paths.
 *
 * Carried on the summary and not only on `PartDetail` because the removed list needs
 * it: that page names a part in a purge confirmation, purge is the one irreversible
 * action in the product, and a confirmation reading "Purge “bracket” permanently?"
 * against two identically named parts is a confirmation that cannot be answered
 * correctly.
 */
sourcePath: string, 
/**
 * The thumbnail derivative's content hash, not a URL. Holding it is not
 * authorization to read it — the API still checks tenant and part reachability.
 */
thumbnail: BlobHash | null, triangleCount: number | null, 
/**
 * True when any geometric figure on this part is mesh-derived.
 */
approximate: boolean, 
/**
 * The revision's source file, or `None` when it has none. All four fields below
 * come from one `file` row and the `blob` row it names, so they are absent
 * together and never disagree.
 *
 * A revision without a source file is not something ingest writes today — it is
 * what a half-repaired database looks like — and such a part still has to appear
 * in the grid, which is why these are optional rather than zeroed. A part the grid
 * silently omits is a part its owner cannot find, delete or re-scan.
 */
sourceHash: BlobHash | null, 
/**
 * The L0 tessellation's content hash — the rung the viewer paints first, and today
 * the only thing that makes those bytes addressable at all.
 *
 * Every ingest writes an L0 glTF, reference-counted and never read, because nothing
 * carried its hash: `GET /api/blob/{blake3}` had no possible caller and roughly
 * 7.5 MB per 1,000 parts was written and unreachable. That is the whole reason this
 * field lands before the viewer that will use it.
 *
 * A hash, not a URL, and holding one is not authorization — `blob::by_hash` asks
 * `PgBlobs::derivative_is_reachable` before serving a byte, exactly as it does for
 * `thumbnail` above. `None` means this revision has no L0 rung: a part ingested
 * before the LOD ladder, or one whose derive job has not run.
 */
tessellationL0: BlobHash | null, 
/**
 * The ingested file's size. `u64` here, `number | null` on the wire: serde writes
 * a JSON number, and ts-rs 12 would otherwise type a 64-bit integer as `bigint`,
 * which is something `JSON.parse` never produces. The override has to spell the
 * null half itself — it replaces the whole type, `Option` included. The precision
 * ceiling this buys is 2^53 bytes, 9 petabytes in one file.
 */
sourceBytes: number | null, 
/**
 * What this part's file actually occupies on disk, after compression. Read off the
 * `file` row beside `source_bytes`, not off the shared `blob` row: source bytes are
 * no longer deduplicated, so a hash can have a compressed copy at the old
 * content-addressed path and a raw copy in a model directory at the same time, and
 * the per-hash column could only ever describe one of them — it reported 91,204 bytes
 * for a 204,800-byte file it had just called uncompressed.
 */
storedBytes: number | null, 
/**
 * Whether the stored bytes are a zstd frame — `blob.zstd_level` is `Some(level)`
 * with `level != 0`, the same predicate `SourceReader::get` decodes on.
 *
 * An unrecorded level (`NULL`) reports `false`, not "unknown" — and not because the
 * download would hand those bytes over raw. It would not: `download.rs` refuses a
 * `NULL` level outright, 500 naming the blob, per spec §2.5.1 and ruling T1-A, so
 * the `None` half of that predicate is unreachable from the only caller.
 *
 * The reason is smaller. This field's own `None` is already spoken for: it means the
 * revision has no source row at all, and a third state would put two unrelated facts
 * on one display field. A `NULL` level is a data error, and the place that reports
 * one is the route that has to refuse to act on it, not a card in a grid.
 *
 * That state is reachable in production, not only from a test's `UPDATE`:
 * `link_existing` does not rewrite an existing `blob` row, and tessellation blobs
 * are written with `zstd_level NULL`, so ingesting bytes byte-identical to a
 * derivative writes a `role = 'source'` file row over a `NULL`-level blob.
 */
compressed: boolean | null, 
/**
 * The box this part has to fit in, in millimetres, X/Y/Z.
 *
 * On the summary and not only on [`PartDetail`] because the grid asks a question the
 * detail page cannot answer: *which* of these fits. A card showing a triangle count
 * and nothing else tells a person how heavy a mesh is, which is not a reason anyone
 * opens a parts library. Every layout the grid now offers reads this — the tile's
 * overlay, the list row's dimension column, and the height filter that hides what
 * will not go on the plate — and none of them could exist while the only route to a
 * bounding box was one request per part.
 *
 * `None` where the revision has no measurement: a part whose derive job has not run,
 * or one ingested before measurement existed. Absent, never zeroed — a zero-size box
 * is a real (if degenerate) measurement, and reporting one for a part nobody has
 * measured would put a figure on a card that no one computed.
 *
 * Three `f64`s and not a struct, matching [`MeshMeasurements::bbox_mm`] and
 * [`PartDetail::bbox_mm`] so a dimension means one thing in all three places.
 */
bboxMm: [number, number, number] | null, 
/**
 * Solid volume in cubic millimetres, or `None` where the revision has none.
 *
 * Here for the same reason `bbox_mm` is, and it is the figure the list layout sorts a
 * column by. Millimetres cubed on the wire and displayed in cm³ — the conversion
 * belongs to the one place that formats it, not to a field every reader would have to
 * remember to divide.
 *
 * ponytail: no per-figure provenance on the card, unlike [`PartDetail`]'s
 * `Approximate<f64>`. The card carries `approximate` for the whole part, and Phase 1
 * ingests only meshes so that flag is unconditionally true — every figure a card shows
 * is tessellated. The trigger to widen this into an `Approximate<f64>` is the first
 * analytic figure reaching a card, which is Phase 2's STEP ingest: from then on a part
 * can carry an analytic volume beside a tessellated triangle count, and one flag for
 * the whole card is wrong about one of them whichever way it is set.
 */
volumeMm3: number | null, createdAt: string, updatedAt: string, };
