// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 *Identifies one picture in a part's gallery. Its own id and not a position, because the gallery is reorderable and a client holding "the second image" would be holding something that changes under it.
 */
export type PartImageId = string;
