// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LockId } from "./LockId";

/**
 * An active check-out, as a part's page shows it.
 */
export type PartLock = { id: LockId, holder: string, takenAt: string, };
