// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 *Identifies one record of where a part came from. A part can carry several — the model from one place and the hardware from another.
 */
export type PartSourceId = string;
