// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PartSourceId } from "./PartSourceId";

/**
 * One source, as the interface reads it.
 */
export type PartSource = { id: PartSourceId, url: string | null, vendor: string | null, 
/**
 * The seller's own identifier — an SKU, a Thingiverse id, a number in their catalogue.
 * Named for what it is rather than `sku`, because it is whatever they call it.
 */
externalId: string | null, title: string | null, 
/**
 * Free text. `DATA.md`: not bureaucracy — somebody selling prints needs to see this.
 */
license: string | null, 
/**
 * Minor units, so 12.50 EUR is 1250. Never a float — a price is money.
 *
 * **`number` on the wire and not `bigint`**, which is what ts-rs emits for an `i64` by
 * default. `JSON.stringify` throws on a BigInt, so the default would make this field
 * unsendable; and a JSON number is exact to 2^53, which in minor units is ninety
 * trillion of any currency. The column stays `bigint` — the narrowing is the wire's,
 * not the store's.
 *
 * ponytail: exact to 2^53 minor units. If a price ever needs more than that, the field
 * becomes a decimal string, not a wider integer.
 */
priceMinor: number | null, 
/**
 * ISO 4217. Meaningless without `price_minor`, which the database also insists on.
 */
currency: string | null, };
