// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PartImageId } from "./PartImageId";

/**
 * One image, ready to render. `src` is a `data:` URL or a blob route — the caller does not
 * need to know which, and the distinction is a storage decision rather than a fact about
 * the picture.
 */
export type PartImage = { id: PartImageId, src: string, 
/**
 * `uploaded`, `url_supplied`, `og_fetched` or `rendered`.
 */
origin: string, 
/**
 * Where it came from, for one that was fetched. Shown so a person can tell an image
 * they chose from one that was pulled in for them.
 */
sourceUrl: string | null, };
