// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One decision about a pair of parts, as `part_link.kind` stores it.
 */
export type PartLinkKind = "variant" | "distinct" | "foldedInto";
