// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Approximate } from "./Approximate";
import type { BlobHash } from "./BlobHash";
import type { RevisionDiff } from "./RevisionDiff";
import type { RevisionId } from "./RevisionId";
import type { RevisionOrigin } from "./RevisionOrigin";

/**
 * One revision in a part's history.
 */
export type PartRevision = { id: RevisionId, 
/**
 * The revision this one was recorded on top of. `None` for a part's first.
 */
parent: RevisionId | null, revLabel: string, origin: RevisionOrigin, createdAt: string, 
/**
 * `data:image/webp;base64,…`, as `PartDetail.thumbnail` is.
 */
thumbnail: string | null, triangleCount: number | null, bboxMm: Approximate<[number, number, number]> | null, volumeMm3: Approximate<number> | null, surfaceAreaMm2: Approximate<number> | null, sourceHash: BlobHash | null, sourceFormat: string | null, sourceBytes: number | null, 
/**
 * What changed from the revision this one was recorded on top of. `None` for a part's
 * first revision.
 */
deltaFromParent: RevisionDiff | null, };
