// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlobHash } from "./BlobHash";
import type { LibraryId } from "./LibraryId";
import type { PartId } from "./PartId";
import type { RevisionId } from "./RevisionId";

/**
 * One grid card — the wire shape, deliberately not `PartSummary`.
 *
 * `PartSummary.thumbnail` is `Option<BlobHash>`: a content hash for a hash-addressed
 * thumbnail endpoint that arrives with the viewer. Slice 1 has no such endpoint — it
 * stores the WebP inline as `bytea` so a grid page costs one query, not a round trip
 * per card — so this type carries the decoded bytes themselves, as a `data:` URL a
 * browser can drop straight into an `<img src>`. Widening `PartSummary` instead would
 * put a transport concern into a domain type the viewer will reuse differently.
 */
export type PartCard = { id: PartId, library: LibraryId, 
/**
 * The revision this card's numbers describe, and the one its download link names.
 * Carried verbatim from `PartSummary.revision` — see there for why the frontend
 * must not resolve "latest" a second time of its own.
 */
revision: RevisionId, name: string, partNumber: string | null, 
/**
 * The path this part is known by — its identity since slice 6a, carried verbatim
 * from `PartSummary`. The removed list names a part by this in its purge
 * confirmation, because two parts can share a name and only one of them is the one
 * being destroyed.
 */
sourcePath: string, 
/**
 * `data:image/webp;base64,<...>`. `None` when the part's latest revision has no
 * thumbnail derivative.
 */
thumbnail: string | null, triangleCount: number | null, 
/**
 * True when *any* geometric figure on this part is mesh-derived — carried
 * verbatim from `PartSummary.approximate`, not narrowed to "every". Every figure
 * on a slice-1 (STL-only) part is tessellated, so this reads `true` today, but the
 * meaning must stay "any" for when analytic B-rep figures arrive alongside mesh
 * ones on the same part.
 */
approximate: boolean, 
/**
 * The source file's hash, `None` when the revision has no source row. Rendered as
 * a short hash beside the download link so a user can check what they got against
 * what the card claimed (`DATA.md` §5.1) — holding it is not authorization to read
 * it, exactly as `PartSummary.thumbnail` is not.
 */
sourceHash: BlobHash | null, 
/**
 * The L0 tessellation's hash, carried verbatim from `PartSummary` for the reason
 * `source_hash` is: it is the only thing that makes those bytes addressable, and
 * `GET /api/blob/{blake3}` had no possible caller without it. Holding it is not
 * authorization — that route checks reachability before serving.
 */
tessellationL0: BlobHash | null, 
/**
 * Ingested size and size on disk, from `PartSummary`. `number | null`, not
 * `bigint`, for the reason given there: it is what serde puts on the wire.
 */
sourceBytes: number | null, storedBytes: number | null, 
/**
 * Whether the stored bytes are a zstd frame. `Some(false)` covers both "stored
 * raw" and "level unrecorded" — see `PartSummary.compressed`.
 */
compressed: boolean | null, 
/**
 * The model's own directory in the store, relative to the storage root:
 * `libraries/default/Terrain/rock`. Shown, never opened — no browser can navigate a
 * `file://` URL from a page, and the api runs in a container where an absolute path
 * would name a filesystem the user is not looking at. The Tauri shell is what will
 * eventually have a host to ask.
 *
 * Kept beside `storagePath` below rather than derived from it, because the two answer
 * different questions and one of them is a *move* target: this is what the move route
 * renames, and what the card offers to move. Deriving it in the client would put a
 * second definition of "the parent of a model file" in TypeScript, next to
 * `model_directory`'s in Rust.
 *
 * `None` is a real state and not a missing value — the part predates the folder layout
 * and its bytes are still content-addressed, so it has no directory to show and cannot
 * be moved until `migrate_storage` reaches it. The card says so rather than offering a
 * move that the route would refuse.
 */
directory: string | null, 
/**
 * The model's file, path and all: `libraries/default/Terrain/rock/rock.stl`.
 *
 * The `directory` above with the filename back on, and the client cannot reconstruct
 * it: `model_dir_for` disambiguates a colliding model name — the second `cliff` becomes
 * `cliff_a1b2c3` — so a path joined from a part's name would be confidently wrong
 * exactly where a person is most likely to be looking for it.
 *
 * Shown, never opened. No browser navigates a `file://` URL from a page, so this is
 * selectable text; and prefixed with `InstanceStorageView::host_storage_root` when the
 * deployment has said where the store is, which is what makes it a path somebody can
 * paste into a file manager rather than one they have to work out.
 *
 * `None` alongside `directory`, and for the same reason.
 */
storagePath: string | null, createdAt: string, updatedAt: string, };
