// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Approximate } from "./Approximate";
import type { BlobHash } from "./BlobHash";
import type { LibraryId } from "./LibraryId";
import type { PartId } from "./PartId";
import type { RevisionId } from "./RevisionId";

/**
 * Everything one part's page shows.
 */
export type PartDetail = { id: PartId, library: LibraryId, 
/**
 * The revision every figure below describes, and the one the download link names.
 * Carried rather than re-resolved for the reason `PartCard` gives: resolving
 * "latest" a second time could name a different revision than these numbers.
 */
revision: RevisionId, 
/**
 * The revision's label — `1` for everything ingest writes today, because a second
 * revision is Phase 4's. Shown rather than hidden so a part that *does* carry one
 * does not silently look like a part that does not.
 */
revLabel: string, name: string, partNumber: string | null, 
/**
 * The part's identity within its library since slice 6a: the path a scan found it
 * at, or the path the browser reported when it was dropped. Two parts named
 * `bracket` in two folders are told apart by this and by nothing else, which is
 * exactly why the page shows it.
 */
sourcePath: string, 
/**
 * `data:image/webp;base64,<...>`, as on the card.
 */
thumbnail: string | null, 
/**
 * Mesh facts. `None` on a revision whose measurements were never written.
 */
triangleCount: number | null, 
/**
 * Whether the mesh is closed. This is the reason `volume` may be absent on a part
 * that plainly has one, so it is shown next to it rather than buried.
 */
isWatertight: boolean | null, 
/**
 * Extent in millimetres, all three axes or none — see `PartDetailRow::bbox_mm`.
 */
bboxMm: Approximate<[number, number, number]> | null, 
/**
 * **Absent for an open mesh, deliberately.** Signed-volume integration over a
 * non-watertight mesh produces a plausible-looking number that means nothing, and
 * `MeshMeasurements::volume_approximate` already refuses to answer for one.
 * "Measurement must not lie" includes declining to measure.
 */
volumeMm3: Approximate<number> | null, surfaceAreaMm2: Approximate<number> | null, 
/**
 * What produced the derivatives — the kernel and its version, as ingest recorded it.
 * Two parts with different values here were measured by different code, which is the
 * first thing to look at when two figures disagree.
 */
kernelVersion: string | null, sourceHash: BlobHash | null, 
/**
 * `stl`, `3mf`, `obj` — what the ingested file actually is, not what its name says.
 */
sourceFormat: string | null, sourceBytes: number | null, storedBytes: number | null, compressed: boolean | null, 
/**
 * The L0 tessellation, and what it occupies. The first honest caller of
 * `GET /api/blob/{blake3}`: until this page, every ingest wrote a rung nothing could
 * address. Showing its hash and size is what tells a user their part has a usable
 * derivative at all.
 */
tessellationL0: BlobHash | null, tessellationL0Bytes: number | null, createdAt: string, updatedAt: string, };
