// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryId } from "./LibraryId";
import type { PartId } from "./PartId";

/**
 * One grid card — the wire shape, deliberately not `PartSummary`.
 *
 * `PartSummary.thumbnail` is `Option<BlobHash>`: a content hash for a hash-addressed
 * thumbnail endpoint that arrives with the viewer. Slice 1 has no such endpoint — it
 * stores the WebP inline as `bytea` so a grid page costs one query, not a round trip
 * per card — so this type carries the decoded bytes themselves, as a `data:` URL a
 * browser can drop straight into an `<img src>`. Widening `PartSummary` instead would
 * put a transport concern into a domain type the viewer will reuse differently.
 */
export type PartCard = { id: PartId, library: LibraryId, name: string, partNumber: string | null, 
/**
 * `data:image/webp;base64,<...>`. `None` when the part's latest revision has no
 * thumbnail derivative.
 */
thumbnail: string | null, triangleCount: number | null, 
/**
 * True when *any* geometric figure on this part is mesh-derived — carried
 * verbatim from `PartSummary.approximate`, not narrowed to "every". Every figure
 * on a slice-1 (STL-only) part is tessellated, so this reads `true` today, but the
 * meaning must stay "any" for when analytic B-rep figures arrive alongside mesh
 * ones on the same part.
 */
approximate: boolean, createdAt: string, updatedAt: string, };
