// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlobHash } from "./BlobHash";
import type { LibraryId } from "./LibraryId";
import type { PartId } from "./PartId";

/**
 * The grid row, in the shape the spec calls for: identity, part number, thumbnail
 * reference, approximate flag, timestamps. Deliberately narrow — the open path reads
 * metadata and derivatives only, never a source file.
 */
export type PartSummary = { id: PartId, library: LibraryId, name: string, partNumber: string | null, 
/**
 * The thumbnail derivative's content hash, not a URL. Holding it is not
 * authorization to read it — the API still checks tenant and part reachability.
 */
thumbnail: BlobHash | null, triangleCount: number | null, 
/**
 * True when every geometric figure on this part is mesh-derived.
 */
approximate: boolean, createdAt: string, updatedAt: string, };
