// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 *Identifies somebody else's share as this installation mirrors it: a local id, never the sharer's own.
 */
export type PeerShareId = string;
