// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Somebody this installation is paired with.
 */
export type Peer = { deviceId: string, address: string, 
/**
 * What they call themselves, as their last hello said.
 */
name: string | null, addedAt: string, lastSeenAt: string | null, 
/**
 * Why the last hello failed, in words. `None` once one succeeds.
 */
lastError: string | null, online: boolean, 
/**
 * Who introduced them, when they arrived on a folder's roster rather than by somebody pasting their id.
 */
introducedBy: string | null, 
/**
 * How many folders this installation still has in common with them. Zero is somebody paired who reaches
 * nothing — every folder they were in has gone — which the page says rather than leaving them looking
 * like anybody else (S10).
 */
foldersInCommon: number, };
