// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Somebody this installation is paired with.
 */
export type Peer = { deviceId: string, address: string, 
/**
 * What they call themselves, as their last hello said.
 */
name: string | null, addedAt: string, lastSeenAt: string | null, 
/**
 * Why the last hello failed, in words. `None` once one succeeds.
 */
lastError: string | null, online: boolean, };
