// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PmiDatum } from "./PmiDatum";
import type { PmiDimension } from "./PmiDimension";
import type { PmiTolerance } from "./PmiTolerance";

/**
 * The product and manufacturing information an AP242 file carries as data: dimensions with their
 * tolerances, geometric tolerances, and the datums those refer to.
 *
 * **Specified, never measured.** These are the numbers a designer wrote into the file, so they are
 * neither exact nor approximate in [`Approximate`](crate::Approximate)'s sense, and nothing here
 * says whether a made part meets them. `OcctKernel` fills this from `occt-bridge`'s `pmi.json`; a
 * mesh has none, and neither does a STEP file whose exporter wrote only geometry.
 */
export type Pmi = { dimensions: Array<PmiDimension>, tolerances: Array<PmiTolerance>, datums: Array<PmiDatum>, };
