// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PmiFace } from "./PmiFace";

/**
 * A dimension, in millimetres or, for an angle, degrees.
 */
export type PmiDimension = { 
/**
 * `diameter`, `radius`, `spherical_diameter`, `spherical_radius`, `thickness`, `angle`,
 * `distance`, or `other` for a kind this reads but does not name.
 */
type: string, value: number, 
/**
 * How far above `value` the size may be, when the file gives plus and minus bounds.
 */
upper: number | null, 
/**
 * How far below `value`, as the file writes it: zero, or a negative deviation.
 */
lower: number | null, faces: Array<PmiFace>, };
