// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PmiFace } from "./PmiFace";

/**
 * A datum: a named feature other tolerances are measured from.
 */
export type PmiDatum = { name: string, faces: Array<PmiFace>, };
