// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A face an annotation applies to, named as an [`Entity`](crate::Entity) names one: the prototype,
 * and the face's 1-based index in that prototype's faces. `face` is `None` when the annotation
 * applies to the whole part rather than to one face of it.
 */
export type PmiFace = { prototype: string, face: number | null, };
