// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PmiFace } from "./PmiFace";

/**
 * A geometric tolerance: the width of the zone a feature's form, orientation or location must
 * stay in, in millimetres.
 */
export type PmiTolerance = { 
/**
 * `flatness`, `perpendicularity`, `position` and the other ISO 1101 characteristics, in
 * snake case, or `other`.
 */
type: string, value: number, 
/**
 * The datums the tolerance is measured from, by name, in the file's order. Empty for a form
 * tolerance such as flatness, which refers to none.
 */
datums: Array<string>, faces: Array<PmiFace>, };
