// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a measured value came from. Persisted as text beside the value it describes,
 * because a single row-level flag cannot describe a revision whose volume is analytic
 * and whose triangle count is tessellated — which is every STEP part from Phase 2 on.
 */
export type Provenance = "analytic" | "tessellated";
