// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchId } from "./BatchId";
import type { LibraryId } from "./LibraryId";
import type { PullId } from "./PullId";

/**
 * A pull, as its share's page follows it: fetching, then importing in `batch_id`, then done or failed.
 */
export type Pull = { id: PullId, libraryId: LibraryId, 
/**
 * `queued`, `fetching`, `importing`, `done` or `failed`.
 */
state: string, filesTotal: number, filesDone: number, bytesTotal: number, bytesDone: number, batchId: BatchId | null, 
/**
 * Why it failed, or why it is waiting to try again.
 */
error: string | null, };
