// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 *Identifies one pull: somebody else's share, fetched into one of this installation's libraries.
 */
export type PullId = string;
