// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchId } from "./BatchId";
import type { LibraryId } from "./LibraryId";
import type { PeerShareId } from "./PeerShareId";
import type { PullId } from "./PullId";

/**
 * A pull, as its share's page follows it: fetching, then importing in `batch_id`, then done or failed.
 *
 * `sourcePath` names the one part it is for (S9); a pull of the whole folder leaves it out.
 */
export type Pull = { id: PullId, 
/**
 * The mirrored share, while this installation still mirrors it.
 */
shareId: PeerShareId | null, 
/**
 * The share's name, kept with the pull, so a pull whose share was withdrawn still says which it was.
 */
shareName: string, 
/**
 * What its sharer calls themselves, as their last hello said.
 */
sharer: string | null, libraryId: LibraryId, 
/**
 * `queued`, `fetching`, `waiting`, `paused`, `importing`, `done` or `failed`.
 */
state: string, filesTotal: number, filesDone: number, bytesTotal: number, bytesDone: number, batchId: BatchId | null, 
/**
 * Why it failed, or why it is waiting to try again.
 */
error: string | null, 
/**
 * The one part it is for (S9), by its path in the folder. `None` is the whole folder.
 */
sourcePath: string | null, 
/**
 * How many unfinished pulls are ahead of this one. One pull runs at a time, so a part opened while
 * another pull is fetching waits, and the page says how long the queue is rather than looking stuck.
 */
queuedBehind: number, };
