// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchId } from "./BatchId";
import type { LibraryId } from "./LibraryId";
import type { PeerShareId } from "./PeerShareId";
import type { PullId } from "./PullId";

/**
 * A pull, as its share's page follows it: fetching, then importing in `batch_id`, then done or failed.
 */
export type Pull = { id: PullId, 
/**
 * The mirrored share, while this installation still mirrors it.
 */
shareId: PeerShareId | null, 
/**
 * The share's name, kept with the pull, so a pull whose share was withdrawn still says which it was.
 */
shareName: string, 
/**
 * What its sharer calls themselves, as their last hello said.
 */
sharer: string | null, libraryId: LibraryId, 
/**
 * `queued`, `fetching`, `waiting`, `paused`, `importing`, `done` or `failed`.
 */
state: string, filesTotal: number, filesDone: number, bytesTotal: number, bytesDone: number, batchId: BatchId | null, 
/**
 * Why it failed, or why it is waiting to try again.
 */
error: string | null, };
