// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a purge did, in the only terms that are true right afterwards.
 *
 * Not "bytes freed". A purge frees nothing on the day it runs — the blobs it orphans sit
 * exactly where they were for thirty days, reachable by hash and restorable, and a number
 * labelled "freed" would be describing something that has not happened. `quarantinedBytes`
 * is what will come back, later, if nobody re-ingests those bytes first.
 */
export type PurgeResult = { 
/**
 * Blobs this purge left with nothing pointing at them.
 */
quarantined: number, 
/**
 * `number`, not `bigint`: ts-rs maps a bare `u64` to `bigint`, which `JSON.parse`
 * never produces — the same correction `PartSummary::source_bytes` carries, for the
 * same reason.
 */
quarantinedBytes: number, };
