// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A library's jobs that are not finished, and the ones that failed.
 */
export type QueueSummary = { pending: number, running: number, failed: number, };
