// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagCount } from "./TagCount";

/**
 * `GET /api/libraries/{id}/tags/related?tag=` — one tag, and the tags it shares parts with.
 */
export type RelatedTags = { 
/**
 * The tag asked about, as it was asked for.
 */
tag: string, 
/**
 * Live parts carrying it. `0` means no live part does: the tag is gone, not merely lonely.
 */
parts: number, 
/**
 * The fewest parts a tag must share to be listed below. On the wire so the sentence naming it
 * cannot drift from the rule.
 */
floor: number, 
/**
 * Other tags on those same parts, most shared first then alphabetically. Each `count` is the
 * number of parts shared with `tag`, not the tag's own total.
 */
related: Array<TagCount>, };
