// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /api/parts/{id}/lock/release`'s body.
 */
export type ReleaseLock = { 
/**
 * Who is releasing it. Recorded, and named to the holder when their next save is refused.
 */
by: string, };
