// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `PATCH /api/libraries/{library}/filters/{filter}`.
 */
export type RenameSavedFilter = { name: string, };
