// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `POST /api/storage/render-cache` answers: the rungs it removed, and the bytes that entered
 * the thirty-day quarantine. Named for what happened, never "freed".
 */
export type RenderCacheFreedView = { removed: number, quarantinedBytes: number, };
