// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyResult } from "./KeyResult";

/**
 * The answer: one [`KeyResult`] per key, in the order asked. Always 200 once the body is valid — a widget
 * that failed or ran out of time says so in its own result, and the others still arrive.
 */
export type ResolveResponse = { results: Array<KeyResult>, };
