// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WidgetRequest } from "./WidgetRequest";

/**
 * The `POST /api/dashboard/resolve` body: 1 to 32 widgets, each key once. Anything else is refused whole (422),
 * so a runaway layout cannot hold the database's connections.
 */
export type ResolveRequest = { widgets: Array<WidgetRequest>, };
