// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a retry did.
 */
export type RetryAccepted = { 
/**
 * How many failed jobs went back in the queue. Zero is an answer rather than an error:
 * the job was retried already, finished another way, or is a migration, which retries
 * itself.
 */
retried: number, };
