// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Delta } from "./Delta";

/**
 * Every figure's change between two revisions of one part.
 *
 * A figure that either revision did not record has no delta — `None`, never a zero. An open
 * mesh has no volume, and a volume change against it would be a number about nothing.
 */
export type RevisionDiff = { volumeMm3: Delta | null, surfaceAreaMm2: Delta | null, 
/**
 * Per axis: x, y, z.
 */
bboxMm: [Delta, Delta, Delta] | null, triangleCount: Delta | null, };
