// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a revision's bytes came from. `revision.origin` holds [`RevisionOrigin::as_str`].
 *
 * Only the revisions Phase 4 writes are told apart. A part's *first* revision is written by
 * `insert_part_chain`, which says `ingest` whichever route the bytes arrived by — recorded
 * in the slice 1 spec (§2) rather than fixed there.
 */
export type RevisionOrigin = "ingest" | "upload" | "agent";
