// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Delta } from "./Delta";

/**
 * Every figure's change between two revisions of one part.
 *
 * A figure that either revision did not record has no delta — `None`, never a zero. An open
 * mesh has no volume, and a volume change against it would be a number about nothing.
 */
export type RevisionDiff = { volumeMm3: Delta | null, surfaceAreaMm2: Delta | null, 
/**
 * Per axis: x, y, z.
 */
bboxMm: [Delta, Delta, Delta] | null, triangleCount: Delta | null, 
/**
 * A CAD revision's B-rep faces and edges, exact. `None` when either revision is a mesh, or was
 * read before the bridge counted them.
 */
faceCount: Delta | null, edgeCount: Delta | null, 
/**
 * Volume times the density of the part's one material as it is today, on both sides: always
 * approximate, since a density is typed. `None` when there is no such density or no volume.
 */
massG: Delta | null, 
/**
 * Per axis: how far the centre of mass moved. Exact only between two B-reps. `None` when either
 * revision was recorded before centres were, or has no volume.
 */
centreMm: [Delta, Delta, Delta] | null, };
