// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 *Identifies one saved filter: a name for a set of the grid's filters in one library.
 */
export type SavedFilterId = string;
