// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterSearch } from "./FilterSearch";
import type { SavedFilterId } from "./SavedFilterId";

/**
 * One saved filter.
 */
export type SavedFilter = { id: SavedFilterId, name: string, search: FilterSearch, };
