// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchId } from "./BatchId";

/**
 * The scan route's response. The work has been accepted, not done.
 */
export type ScanAccepted = { batchId: BatchId, 
/**
 * How many jobs were enqueued. Zero is a success, not an error — and a batch with
 * zero jobs has no status resource, so the client must not poll. Not a file count:
 * the thumbnail routes answer with revisions, and a scan answers with `1`, the one
 * `scan_directory` job whose own walk grows the batch as it finds candidates.
 */
queued: number, };
