// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchId } from "./BatchId";

/**
 * The scan route's response. The work has been accepted, not done.
 */
export type ScanAccepted = { batchId: BatchId, 
/**
 * How many `*.stl` candidates were enqueued. Zero is a success, not an error --
 * and a batch with zero jobs has no status resource, so the client must not poll.
 */
queued: number, };
