// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `PUT /api/parts/{id}/fields/{key}`: the part's value for one field, or `null` to clear it.
 */
export type SetFieldValue = { value: string | number | null, };
