// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a picture should sit in its frame.
 *
 * A whole framing rather than a patch of one: there are three fields, a person adjusting
 * one is looking at the other two, and "omitted means unchanged" is a distinction worth
 * having only when the fields are independent — `FolderPatch` needed it because a rename
 * and a move are different intents, and these are one.
 */
export type SetFraming = { fit: string, focusX: number, focusY: number, };
