// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PartLinkKind } from "./PartLinkKind";

/**
 * The `PUT /api/parts/{id}/links/{other}` body. `foldedInto` is refused here — folding soft-removes a part, and
 * is [`FoldPart`]'s.
 */
export type SetLink = { kind: PartLinkKind, };
