// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `PUT /api/shares/{id}/members`'s body: the whole list, not a change to it.
 */
export type SetMembers = { deviceIds: Array<string>, };
