// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `PUT` body: every material the part has afterwards. An empty list hands the part back to
 * what its file states.
 */
export type SetMaterials = { materials: Array<string>, };
