// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `PUT` body: every material the part has afterwards. An empty list says the part holds no
 * material, and is kept over what its file states like any other typed list; `DELETE` on the same
 * path is what hands the part back to the file.
 */
export type SetMaterials = { materials: Array<string>, };
