// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `PUT` body. `None`, or nothing but spaces, clears the name.
 */
export type SetSharingName = { name: string | null, };
