// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FolderId } from "./FolderId";

/**
 * The `POST` body.
 */
export type ShareCategory = { folderId: FolderId, };
