// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShareId } from "./ShareId";

/**
 * Somebody who asked for a share's files.
 */
export type ShareRequest = { shareId: ShareId, shareName: string, deviceId: string, 
/**
 * What they call themselves, as their last hello said.
 */
name: string | null, 
/**
 * `asked`, `granted` or `denied`.
 */
state: string, askedAt: string, };
