// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FolderId } from "./FolderId";

/**
 * The `POST` body.
 */
export type ShareCategory = { folderId: FolderId, 
/**
 * Ask before anyone fetches its files. Left out, a new share is open and an existing one keeps what it had.
 */
asksFirst?: boolean, 
/**
 * Who it goes to. Left out, a new share reaches everyone paired and an existing one keeps its list, so
 * sharing a folder the way it has always been shared stays one call with one field.
 */
memberDeviceIds?: Array<string>, };
