// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * This installation, as the people it shares with know it.
 */
export type SharingIdentity = { 
/**
 * `None` until the peer role has run here, which is what sharing switched off looks like.
 */
deviceId: string | null, name: string | null, };
