// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 *Identifies one category this installation offers the people it is paired with, and everything under it.
 */
export type ShareId = string;
