// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FolderId } from "./FolderId";
import type { ShareId } from "./ShareId";

/**
 * A category of one library that this installation shares.
 */
export type SharedCategory = { id: ShareId, folderId: FolderId, name: string, createdAt: string, };
