// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One person a share goes to.
 */
export type ShareMember = { deviceId: string, 
/**
 * What they call themselves, as their last hello said.
 */
name: string | null, address: string, online: boolean, addedAt: string, };
