// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Somebody a part was pulled from: their name when they gave one, and their device id either way.
 */
export type SharedBy = { deviceId: string, name: string | null, };
