// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShareId } from "./ShareId";

/**
 * Everything this installation shares, as its sharing page lists it.
 */
export type ShareSummary = { id: ShareId, name: string, partCount: number, };
