// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryId } from "./LibraryId";

/**
 * `POST /api/sharing/shares/{id}/pulls`'s body: the library the share's parts land in.
 */
export type StartPull = { libraryId: LibraryId, 
/**
 * The one part to pull, by its path in the folder. Left out pulls the whole folder, as this always did.
 */
sourcePath?: string, };
