// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PartImageId } from "./PartImageId";

/**
 * What an upload produced: the id to address it by, and the size it was stored at.
 *
 * The size is here because the resize is otherwise invisible. A photograph over
 * `MAX_EDGE_PX` on its long edge is scaled down on the way in, and a person who attached a
 * 4000-pixel picture is owed the sentence saying what is now on the card.
 */
export type StoredImage = { id: PartImageId, width: number, height: number, };
