// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One tag, and how many of a library's live parts carry it.
 *
 * Not [`crate::parts::FacetValue`], whose `count` is nullable: the facet panel withholds counts past
 * `EXACT_FACET_ROWS`, and these two reads never do, because the count is what the index is ordered by.
 */
export type TagCount = { value: string, 
/**
 * Live parts carrying it, always exact. `u64` would export as `bigint`.
 */
count: number, };
