// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagCount } from "./TagCount";

/**
 * `GET /api/libraries/{id}/tags` — every tag in the library, most-carried first then alphabetically.
 */
export type TagIndex = { tags: Array<TagCount>, };
