// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How many faces and edges a CAD kernel counted on a B-rep, every one of them, analytic or not. A mesh has
 * no B-rep, so it has none, and a diff leaves the counts out rather than comparing a mesh's triangles to
 * a solid's faces.
 */
export type Topology = { faces: number, edges: number, };
