// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UploadFile } from "./UploadFile";

/**
 * What the client is offering, whole. The probe and the commit take the same list — they
 * are the same question asked before and after the transfer — so they take the same
 * type rather than two that must be kept in step.
 */
export type UploadManifest = { files: Array<UploadFile>, };
