// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the client has to do, per file, sorted into three answers.
 *
 * `DATA.md` describes two lists. The third is where the larger win is: `have` only
 * catches a re-import into the *same* library at the *same* path, while `needRows`
 * catches every file whose bytes are already in the store for any reason — a second
 * library, a moved file, the same model downloaded twice — and skips its transfer
 * entirely.
 */
export type UploadPlan = { 
/**
 * This library already indexes these bytes at this path. Nothing to send, nothing
 * to commit.
 */
have: Array<string>, 
/**
 * The bytes are in the store; only the rows are missing. Commit without
 * transferring.
 */
needRows: Array<string>, 
/**
 * Send these.
 */
needBytes: Array<string>, };
