// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlobHash } from "./BlobHash";

/**
 * One file the client is offering: the path it will be known by, and the hash it claims
 * the bytes have.
 */
export type UploadFile = { 
/**
 * Relative to the folder that was dropped, `/`-separated — the browser's own
 * `webkitRelativePath`. This is the `source_path` that gives the part its identity
 * within the library, which is what makes an uploaded folder and a scanned folder
 * the same thing in the database.
 */
path: string, blake3: BlobHash, };
