// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DuplicateSummary } from "./DuplicateSummary";
import type { FacetValue } from "./FacetValue";
import type { FilteredParts } from "./FilteredParts";
import type { InstanceStorageView } from "./InstanceStorageView";
import type { LibraryStorage } from "./LibraryStorage";
import type { PartCard } from "./PartCard";
import type { QueueSummary } from "./QueueSummary";

/**
 * A widget's value, tagged by the same `kind` as the [`Widget`] it answers.
 */
export type WidgetValue = { "kind": "storage", "value": LibraryStorage } | { "kind": "instanceStorage", "value": InstanceStorageView } | { "kind": "recent", "value": Array<PartCard> } | { "kind": "savedFilter", "value": FilteredParts } | { "kind": "facet", "value": Array<FacetValue> } | { "kind": "queue", "value": QueueSummary } | { "kind": "duplicates", "value": DuplicateSummary };
