// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Widget } from "./Widget";

/**
 * One widget asked for, under the key the layout knows it by.
 */
export type WidgetRequest = { key: string, widget: Widget, };
