// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WidgetValue } from "./WidgetValue";

/**
 * How one widget came out.
 */
export type WidgetResult = { "status": "ok", value: WidgetValue, } | { "status": "timedOut" } | { "status": "failed", message: string, };
