/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DuplicatesRouteImport } from './routes/duplicates'
import { Route as RemovedRouteImport } from './routes/removed'
import { Route as SharingRouteImport } from './routes/sharing'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as PartsPartIdRouteImport } from './routes/parts.$partId'
import { Route as TagsTagRouteImport } from './routes/tags_.$tag'
import { Route as SharingSharesShareIdRouteImport } from './routes/sharing_.shares.$shareId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DuplicatesRoute = DuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => rootRouteImport,
} as any)
const RemovedRoute = RemovedRouteImport.update({
  id: '/removed',
  path: '/removed',
  getParentRoute: () => rootRouteImport,
} as any)
const SharingRoute = SharingRouteImport.update({
  id: '/sharing',
  path: '/sharing',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsPartIdRoute = PartsPartIdRouteImport.update({
  id: '/parts/$partId',
  path: '/parts/$partId',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsTagRoute = TagsTagRouteImport.update({
  id: '/tags_/$tag',
  path: '/tags/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const SharingSharesShareIdRoute = SharingSharesShareIdRouteImport.update({
  id: '/sharing_/shares/$shareId',
  path: '/sharing/shares/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/duplicates': typeof DuplicatesRoute
  '/removed': typeof RemovedRoute
  '/sharing': typeof SharingRoute
  '/tags': typeof TagsRoute
  '/parts/$partId': typeof PartsPartIdRoute
  '/tags/$tag': typeof TagsTagRoute
  '/sharing/shares/$shareId': typeof SharingSharesShareIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/duplicates': typeof DuplicatesRoute
  '/removed': typeof RemovedRoute
  '/sharing': typeof SharingRoute
  '/tags': typeof TagsRoute
  '/parts/$partId': typeof PartsPartIdRoute
  '/tags/$tag': typeof TagsTagRoute
  '/sharing/shares/$shareId': typeof SharingSharesShareIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/duplicates': typeof DuplicatesRoute
  '/removed': typeof RemovedRoute
  '/sharing': typeof SharingRoute
  '/tags': typeof TagsRoute
  '/parts/$partId': typeof PartsPartIdRoute
  '/tags_/$tag': typeof TagsTagRoute
  '/sharing_/shares/$shareId': typeof SharingSharesShareIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/duplicates'
    | '/removed'
    | '/sharing'
    | '/tags'
    | '/parts/$partId'
    | '/tags/$tag'
    | '/sharing/shares/$shareId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/duplicates'
    | '/removed'
    | '/sharing'
    | '/tags'
    | '/parts/$partId'
    | '/tags/$tag'
    | '/sharing/shares/$shareId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/duplicates'
    | '/removed'
    | '/sharing'
    | '/tags'
    | '/parts/$partId'
    | '/tags_/$tag'
    | '/sharing_/shares/$shareId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DuplicatesRoute: typeof DuplicatesRoute
  RemovedRoute: typeof RemovedRoute
  SharingRoute: typeof SharingRoute
  TagsRoute: typeof TagsRoute
  PartsPartIdRoute: typeof PartsPartIdRoute
  TagsTagRoute: typeof TagsTagRoute
  SharingSharesShareIdRoute: typeof SharingSharesShareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duplicates': {
      id: '/duplicates'
      path: '/duplicates'
      fullPath: '/duplicates'
      preLoaderRoute: typeof DuplicatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/removed': {
      id: '/removed'
      path: '/removed'
      fullPath: '/removed'
      preLoaderRoute: typeof RemovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sharing': {
      id: '/sharing'
      path: '/sharing'
      fullPath: '/sharing'
      preLoaderRoute: typeof SharingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts/$partId': {
      id: '/parts/$partId'
      path: '/parts/$partId'
      fullPath: '/parts/$partId'
      preLoaderRoute: typeof PartsPartIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags_/$tag': {
      id: '/tags_/$tag'
      path: '/tags/$tag'
      fullPath: '/tags/$tag'
      preLoaderRoute: typeof TagsTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sharing_/shares/$shareId': {
      id: '/sharing_/shares/$shareId'
      path: '/sharing/shares/$shareId'
      fullPath: '/sharing/shares/$shareId'
      preLoaderRoute: typeof SharingSharesShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DuplicatesRoute: DuplicatesRoute,
  RemovedRoute: RemovedRoute,
  SharingRoute: SharingRoute,
  TagsRoute: TagsRoute,
  PartsPartIdRoute: PartsPartIdRoute,
  TagsTagRoute: TagsTagRoute,
  SharingSharesShareIdRoute: SharingSharesShareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
