/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RemovedRouteImport } from './routes/removed'
import { Route as SharingRouteImport } from './routes/sharing'
import { Route as PartsPartIdRouteImport } from './routes/parts.$partId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RemovedRoute = RemovedRouteImport.update({
  id: '/removed',
  path: '/removed',
  getParentRoute: () => rootRouteImport,
} as any)
const SharingRoute = SharingRouteImport.update({
  id: '/sharing',
  path: '/sharing',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsPartIdRoute = PartsPartIdRouteImport.update({
  id: '/parts/$partId',
  path: '/parts/$partId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/removed': typeof RemovedRoute
  '/sharing': typeof SharingRoute
  '/parts/$partId': typeof PartsPartIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/removed': typeof RemovedRoute
  '/sharing': typeof SharingRoute
  '/parts/$partId': typeof PartsPartIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/removed': typeof RemovedRoute
  '/sharing': typeof SharingRoute
  '/parts/$partId': typeof PartsPartIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/removed' | '/sharing' | '/parts/$partId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/removed' | '/sharing' | '/parts/$partId'
  id: '__root__' | '/' | '/removed' | '/sharing' | '/parts/$partId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RemovedRoute: typeof RemovedRoute
  SharingRoute: typeof SharingRoute
  PartsPartIdRoute: typeof PartsPartIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/removed': {
      id: '/removed'
      path: '/removed'
      fullPath: '/removed'
      preLoaderRoute: typeof RemovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sharing': {
      id: '/sharing'
      path: '/sharing'
      fullPath: '/sharing'
      preLoaderRoute: typeof SharingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts/$partId': {
      id: '/parts/$partId'
      path: '/parts/$partId'
      fullPath: '/parts/$partId'
      preLoaderRoute: typeof PartsPartIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RemovedRoute: RemovedRoute,
  SharingRoute: SharingRoute,
  PartsPartIdRoute: PartsPartIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
